name = "JSPEC"
uuid = "799228a4-d83e-4675-bef0-fa04f023a533"
authors = ["Stefano Covino <stefano.covino@inaf.it> and contributors"]
version = "0.1.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
